### ISSUE TITLE
$or is not working on the demo examples

### ISSUE THREAD

**Issue by bahmutov** [nolanlawson/pouchdb-find#155]
Hi,

Great demo at http://nolanlawson.github.io/pouchdb-find/ but here is a weird thing.
`$and` seems to work fine, for example
```js
// Multi-field queries and sorting are also supported
db.createIndex({
  index: {fields: ['series', 'debut']}
}).then(function () {
  return db.find({
    selector: {
      $and: [
        {series: {$eq: 'Mario'}},
        {debut: {$eq: 1990}}
      ]
    }
  });
});
```
but if I replace `$and` with `$or` then I get index error (even though both indices are there)
```js
// Multi-field queries and sorting are also supported
db.createIndex({
  index: {fields: ['series', 'debut']}
}).then(function () {
  return db.find({
    selector: {
      or: [
        {series: {$eq: 'Mario'}},
        {debut: {$eq: 1990}}
      ]
    }
  });
});
```
Error
```
Error: couldn't find a usable index. try creating an index on: or. Make sure that only $eq, $gt, $gte, $lt, and $lte are used for the indexed fields.
    at createNoIndexFoundError (http://nolanlawson.github.io/pouchdb-find/dist/pouchdb.find.js:2145:10)
    at planQuery (http://nolanlawson.github.io/pouchdb-find/dist/pouchdb.find.js:2166:11)
    at http://nolanlawson.github.io/pouchdb-find/dist/pouchdb.find.js:1663:21
```

**Comment by nolanlawson** [comment]
The issue here is the `debut` selector, which can't work with the `['series', 'debut']` index because `series` is first, not `debug`. In this case, the user would indeed be expected to create an index on `debut`.
